run tests of each module separately

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -31,11 +31,17 @@ jobs:
       - name: Run tests
         run: |
           rye sync
-          rye test --all || exit_code=$?
-          if [ "$exit_code" -eq 5 ]; then
-            echo "Some modules don't have any tests. Ignoring exit code 5."
-            exit 0
-          else
-            exit $exit_code
-          fi
+          exit_code=0
+          members=$(rye show | awk '/members:/{flag=1; next} /configured sources:/{flag=0} flag' | awk '{print $1}')
+          for member in $members; do
+            echo "Running tests for $member"
+            rye test --package $member || workspace_exit_code=$?
+            if [ "$workspace_exit_code" -eq 5 ]; then
+              echo "Workspace $member has no tests. Ignoring exit code 5."
+            elif [ "$workspace_exit_code" -ne 0 ]; then
+              echo "Workspace $member tests failed with exit code $workspace_exit_code."
+              exit_code=$workspace_exit_code
+            fi
+          done
+          exit $exit_code
 
