publish fixes

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -14,6 +14,7 @@ on:
 
 env:
   RYE_VERSION: '0.34.0'
+  MAIN_BRANCH: main
 
 permissions:
   id-token: write
@@ -25,6 +26,22 @@ jobs:
     #      major_version: ${{ steps.determine_next_version.outputs.MAJOR_VERSION }}
     #      minor_version: ${{ steps.determine_next_version.outputs.MINOR_VERSION }}
     steps:
+      - name: Verify branch conditions based on minor-release input
+        run: |
+          minor_release="${{ inputs.patch-release }}"
+          branch_name="${GITHUB_REF_NAME}"
+          main_branch="${{ env.MAIN_BRANCH }}"
+          
+          if [ "$minor_release" == "true" ] && [ "$branch_name" == "$main_branch" ]; then
+            echo "Error: minor-release is set to true, but this action is running on the main branch."
+            exit 1
+          elif [ "$minor_release" == "false" ] && [ "$branch_name" != "$main_branch" ]; then
+            echo "Error: minor-release is set to false, but this action is not running on the main branch."
+            exit 1
+          fi
+          
+          echo "Branch verification passed."
+
       - uses: actions/checkout@v4
 
       #      - name: Get the latest release tag
@@ -100,20 +117,20 @@ jobs:
           rye sync
           rye build --all
 
-      - name: Publish package distributions to PyPI
-        uses: pypa/gh-action-pypi-publish@release/v1
-        with:
-          password: ${{ secrets.PYPI_TOKEN }}
+      # - name: Publish package distributions to PyPI
+      #   uses: pypa/gh-action-pypi-publish@release/v1
+      #   with:
+      #     password: ${{ secrets.PYPI_TOKEN }}
 
-      - name: Create a new release
-        uses: actions/create-release@v1
-        env:
-          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
-        with:
-          tag_name: ${{ inputs.release-version }}
-          release_name: Release ${{ inputs.release-version }}
-          draft: false
-          prerelease: false
+      # - name: Create a new release
+      #   uses: actions/create-release@v1
+      #   env:
+      #     GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
+      #   with:
+      #     tag_name: ${{ inputs.release-version }}
+      #     release_name: Release ${{ inputs.release-version }}
+      #     draft: false
+      #     prerelease: false
 
   build-dockers:
     needs: [ publish ]
@@ -121,6 +138,7 @@ jobs:
       fail-fast: false
       matrix:
         module:
+          - core
           - cnv
           - single_cell
     uses: ./.github/workflows/build-workspace-docker.yml
@@ -136,7 +154,7 @@ jobs:
     steps:
       - uses: actions/checkout@v4
         with:
-          fetch-depth: 0
+          ref: ${{ env.MAIN_BRANCH }}
 
       - name: Set next dev version
         id: set_next_version
