ugbio modules

diff --git a/.github/workflows/publish.yml b/.github/workflows/publish.yml
--- a/.github/workflows/publish.yml
+++ b/.github/workflows/publish.yml
@@ -1,51 +1,77 @@
-name: Build and publish to pypi
+name: Ugbio Release
 
 on:
-  release:
-    types: [ created ]
   workflow_dispatch:
     inputs:
-      version:
-        type: string
-        description: "Version to publish modules with"
+      patch-release:
+        description: 'Is this a minor release?'
+        type: boolean
         required: true
+        default: false
 
 env:
   RYE_VERSION: '0.34.0'
+  MAIN_BRANCH: main
+  VERSION_LEVEL: >
+    ${{ fromJson('{
+      true: "patch",
+      false: "minor"
+    }')[github.event.inputs.patch-release] }}
+  DEV_VERSION_LEVEL: >
+    ${{ fromJson('{
+      true: "prepatch",
+      false: "preminor"
+    }')[github.event.inputs.patch-release] }}
+
 permissions:
   id-token: write
-  contents: read
+  contents: write
 jobs:
-  build:
+  publish:
     runs-on: ubuntu-latest
+    outputs:
+      publish_commit_sha: ${{ steps.commit-and-push-1.outputs.commit_long_sha }}
+      new_version: ${{ steps.bump-semver.outputs.new_version }}
     steps:
+      - name: Verify branch conditions based on minor-release input
+        run: |
+          patch_release="${{ inputs.patch-release }}"
+          branch_name="${GITHUB_REF_NAME}"
+          main_branch="${{ env.MAIN_BRANCH }}"
+          
+          if [ "$patch_release" == "true" ] && [ "$branch_name" == "$main_branch" ]; then
+            echo "Error: minor-release is set to true, but this action is running on the main branch."
+            exit 1
+          elif [ "$patch_release" == "false" ] && [ "$branch_name" != "$main_branch" ]; then
+            echo "Error: minor-release is set to false, but this action is not running on the main branch."
+            exit 1
+          fi
+          
+          echo "Branch verification passed."
+
       - uses: actions/checkout@v4
+
+      - uses: actions-ecosystem/action-get-latest-tag@v1
+        id: get-latest-tag
+        with:
+          semver_only: true
+          initial_version: "1.0.0"
+
+      - uses: actions-ecosystem/action-bump-semver@v1
+        id: bump-semver
+        with:
+          current_version: ${{ steps.get-latest-tag.outputs.tag }}
+          level: ${{ env.VERSION_LEVEL }}
+
       - name: Install rye
         uses: eifinger/setup-rye@v3
         with:
           version: ${{ env.RYE_VERSION }}
 
-      - name: Set up Python
-        uses: actions/setup-python@v4
+      - uses: ./.github/actions/update-workspaces-version
         with:
-          python-version: '3.11'
-
-      - name: Install dependencies
-        run: pip install tomli_w
-
-      - name: Update pyproject.toml files with new version
-        id: update_version
-        run: python .github/utils/update_project_version.py ${{ github.event.release.tag_name || inputs.version }}
-
-      - name: Commit and push changes
-        if: github.event_name == 'release'
-        env:
-          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
-        run: |
-          git config --global user.name 'github-actions[bot]'
-          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
-          git commit -am "Update pyproject.toml versions to ${{ github.event.release.tag_name || inputs.version }}"
-          git push
+           version: ${{ steps.bump-semver.outputs.new_version }}
+           ref: ${{ env.GITHUB_REF_NAME }}
 
       - name: Rye build
         run: |
@@ -57,3 +83,46 @@ jobs:
         with:
           password: ${{ secrets.PYPI_TOKEN }}
 
+      - name: Create a new release
+        uses: actions/create-release@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
+        with:
+          tag_name: ${{ steps.bump-semver.outputs.new_version }}
+          release_name: Release ${{ steps.bump-semver.outputs.new_version }}
+          draft: false
+          prerelease: false
+
+  build-dockers:
+    needs: [ publish ]
+    strategy:
+      fail-fast: false
+      matrix:
+        module:
+          - core
+          - cnv
+          - single_cell
+    uses: ./.github/workflows/build-workspace-docker.yml
+    with:
+      docker-file: src/${{ matrix.module }}/Dockerfile
+      docker-image: ugbio_${{ matrix.module }}
+      commit-sha: ${{ needs.publish.outputs.publish_commit_sha }}
+
+  set-dev-version:
+    runs-on: ubuntu-latest
+    needs: [ publish ]
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          ref: ${{ env.GITHUB_REF_NAME }}
+
+      - uses: actions-ecosystem/action-bump-semver@v1
+        id: bump-dev-semver
+        with:
+          current_version: ${{ needs.publish.outputs.new_version }}
+          level: ${{ env.DEV_VERSION_LEVEL }}
+
+      - uses: ./.github/actions/update-workspaces-version
+        with:
+          version: ${{ steps.bump-dev-semver.outputs.new_version }}
+          ref: ${{ env.GITHUB_REF_NAME }}
